---
-name: Installing captive portal dependencies
  apt: 
    name={{ item }} 
    state=installed
    with_items:
       - conntrack
       - psmisc
       
-name: Adding sudo rules for captive portal
  lineinfile:
    dest=/etc/sudoers
    line={{ item }}
    with_items:
      - {{ apache__user }} ALL = NOPASSWD: /sbin/iptables -I internet 1 -t mangle -m mac --mac-source ??\:??\:??\:??\:??\:?? -j RETURN
      - {{ apache__user }} ALL = NOPASSWD: /sbin/iptables -D internet -t mangle -m mac --mac-source ??\:??\:??\:??\:??\:?? -j RETURN
      - {{ apache__user }}  ALL = NOPASSWD: /usr/bin/rmtrack [0-9]*.[0-9]*.[0-9]*.[0-9]*
       
- name: Linking portal content
  file: 
    path:  "{{ apache_docroot }}/portal/main" 
    src: "{{ data_dir }}/provision/ansible/roles/portal/web"
    state: link
    
- name: Deploying captive portal login page
  template:
    src="landing_page/index.php.j2"
    dest="{{ apache_docroot }}/portal/auth/index.php"
