---
- name: Installing portal dependencies
  apt:
    name="{{ item }}"
    state=installed
  with_items:
     - conntrack
     - psmisc

- name: Linking portal content
  file: 
    path="{{ portal__docroot }}" 
    src="{{ data_dir }}/provision/ansible/roles/portal/web"
    state=link

- name: Installing rmtrack script
  copy:
    src=rmtrack
    dest="/usr/bin/"
    mode=0755

- name: Installing portal landing page
  template:
    src="site/index.php.j2"
    dest="{{ portal__docroot }}/index.php"

- name: Creating portal data dir 
  file:
    path="{{ portal__data }}"
    state="directory"
    
- include: captive.yml
  when: {{ portal__require_login }}
