---
- name: Create site content dir
  file: > 
    path="{{ vidtest__docroot }}"
    state=directory
    owner=root group={{ common_web_user }} mode=755 

- name: Deploy site content
  template: >
    src=site/index.html.j2
    dest={{ vidtest__docroot }}/index.html
    
- name: Deploy site redirect instructions
  template: >
    src=config/nginx_portal_redirect.j2
    dest={{ portal__redirects }}/vidtest
    owner=root group={{ common_web_user }} mode=0640
    
- name: Deploy site config
  template: >
    src=config/nginx_server.j2
    dest={{ nginx_sites_available_dir }}/vidtest
    owner=root group={{ common_web_user }} mode=0640

- name: Activate site config
  file: >
    src={{ nginx_sites_available_dir }}/vidtest
    dest={{ nginx_sites_enabled_dir }}/vidtest
    state=link owner=root group=root
  notify: reload nginx
