---
- name: Creating {{ provision__base_dir }}/bin
  file:
    path: "{{ provision__base_dir }}/bin"
    state: directory

- name: Adding drive setup script
  template:
    src: "mount_external_drive.j2"
    dest: "{{ provision__base_dir }}/bin/mount_external_drive"
    owner: root
    mode: 0744

- name: Creating mountpoint {{ external_data_drive__mountpoint }}
  file:
    path: "{{ external_data_drive__mountpoint }}"
    state: directory

- name: Adding udev rule
  template:
    src: "data_drive.rules.j2"
    dest: "/etc/udev/rules.d/data_drive.rules"
