---
- name: nginx must be installed
  apt:
    name=nginx
    state=installed
    
- name: nginx must be running
  service:
    name=nginx
    state=running

- name: Create site content dirs
  file: 
    path={{ item }}
    state=directory
    owner=root group={{ common_web_user }} mode=755 
  with_items:
    - "{{ portal__docroot }}"
    - "{{ portal__redirects }}"

- name: Deploy site content
  template:
    src=site/index.html.j2
    dest={{ portal__docroot }}/index.html
    
- name: Deploy site config
  template:
    src=config/portal.j2
    dest={{ nginx_sites_available_dir }}/portal
    owner=root group={{ common_web_user }} mode=0640

- name: Activate site config
  file:
    src={{ nginx_sites_available_dir }}/portal
    dest={{ nginx_sites_enabled_dir }}/portal
    state=link owner=root group=root
  notify: reload nginx
  
- include: portal_site.yml
  #vars:
  #    portal_subsite__docroot: "{{ portal_subsite__docroot }}"
  #    portal_subsite__urlpath: "{{ portal_subsite__urlpath }}"
  #    portal_subsite__port: "{{ portal_subsite__port }}"
    

