---
- name: Installing dependencies
  apt: name={{ item }} state=installed
  with_items:
    - sqlite3
    - git

- name: Adding alias to /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 kalite"

# This need to only happen if /ansible exists
# can't use it in all cases, e.g. bootstrapping
- name: Checking mount status of {{ kalite__provision__base_dir }}
  shell: mount | grep {{ kalite__provision__base_dir }}
  register: is_mounted
  ignore_errors: True

- name: Creating data dir {{ kalite__provision__base_dir }}
  file: path={{ kalite__provision__base_dir }} state=directory force=no
  when: is_mounted|failed

#- name: Mounting {{ kalite__provision__base_dir }}
#  command: mount --bind data {{ kalite__provision__base_dir }}
#  when: is_mounted|failed 

- name: Getting kalite code
  git: repo={{ kalite__git_source }} dest={{ kalite__provision__base_dir }}

- name: Set kalite user
  file: path={{ kalite__provision__base_dir }} owner={{ kalite__user }} recurse=true

- name: Setting up kalite
  command: kalite/manage.py setup -u teacher -p Tunapanda2 -o kalite -d "Tunapanda classroom server" -n
  args:
    chdir: "{{ kalite__provision__base_dir }}"
    creates: "{{ kalite__provision__base_dir }}/kalite/database/data.sqlite"
  sudo: yes
  sudo_user: "{{  kalite__user }}"
  notify: restart kalite

- name: Installing kalite init script
  command: scripts/runatboot.sh
  args:
    chdir: "{{ kalite__provision__base_dir }}"
    creates: "/etc/init.d/kalite"
  notify: restart kalite

