---
dependencies:
  - common
  - role: nginx
    nginx_sites:
    - cms
    - lms
    - forum
    - xqueue
    - certs
    - lms
    - cms
  - edxlocal
  - mongo
  - { role: 'edxapp', celery_worker: True }
  - edxapp
  - demo
  - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
  - oraclejdk
  - elasticsearch
  - forum
  - { role: "xqueue", update_users: True }
  - certs
  - role: analytics-api
    when: ANALYTICS_API_GIT_IDENTITY
  when: !edx__pre_installed

dependencies:
  - role: portal
    portal__subsites:
      - name: "edx_lms" 
        urlpath: "{{ edx__lms_urlpath }}"
        port: "{{ edx__lms_port }}"
      - name: "edx_cms" 
        urlpath: "{{ edx__cms_urlpath }}"
        port: "{{ edx__cms_port }}"
