---
    vidtest__enabled: false
    vidtest__docroot: "{{ provision__base_dir }}/provision/playbooks/roles/vidtest/data/site"
    vidtest__urlpath: "/vidtest"
    vidtest__extra:   "    rewrite {{ vidtest__urlpath }}/rand[0-9]+(.*)$ {{ vidtest__urlpath }}/$1;"
