---
# Need to load module bcmdhd. Edit /etc/modules to include bcmdhd
# TODO: This does not actually reload the module with the desired arguments
# There must be a reliable way that doesn't require a reboot. Investigate.
- lineinfile:
    dest=/etc/modules
    line="bcmdhd op_mode=2"
    regexp="^bcmdhd"

- name: "Load wlan driver"
  command: modprobe bcmdhd
  ignore_errors: yes

# Install the package "hostapd"
- apt: name=hostapd state=present

- name: hostapd configuration
  template:
      src="hostapd-conf.j2"
      dest=/etc/hostapd.conf
      backup=yes

- name: set hostapd to use config file
  lineinfile: 
      dest=/etc/default/hostapd
      regexp="^DAEMON_CONF=.*"
      line="DAEMON_CONF=/etc/hostapd.conf"
  notify: restart hostapd

- name: IP masquerading
  template:
      src="firewall/masquerade.j2"
      dest="{{ iptables__rules_dir }}/masquerade"
      backup=yes
  notify:
    - reload iptables

