---
portal__enabled: false
portal__port: 80
portal__title: "x2go - Education in a box"
portal__base: "{{ provision__data_dir }}/portal"
portal__docroot: "{{ portal__base }}/main"
portal__redirects: "{{ portal__base }}/sites.d"
portal__users: "{{ portal__base }}/users"
portal__lan: "{{ ansible_wlan1 }}"
portal__inet: "{{ ansible_eth0 }}"
portal__redirect: "{{ ansible_eth0 }}" 
portal__require_login: false
portal__capture_chain: "captive"
portal__subsites: []
nginx_sites_available_dir: "/edx/app/nginx/sites-available/"
nginx_sites_enabled_dir: "/edx/app/nginx/sites-enabled/"


# TODO should go elsehwere
common_web_user: www-data
