---
portal__enabled: false
portal__port: 80
portal__title: "x2go - Education in a box"
portal__base: "{{ provision__data_dir }}/portal"
portal__docroot: "{{ provision__base_dir }}/provision/playbooks/roles/portal/data/site"
portal__redirects: "{{ portal__base }}/sites.d"
portal__users: "{{ portal__base }}/users"
portal__require_login: false
portal__capture_chain: "captive"
# TODO figure out a way to get IP from ifupdown_external_interface
portal__redirect: "{{ ansible_eth0 }}" 
