---
- name: Cubietruck 
  tasks:
    - name: Configure wlan driver
      lineinfile:
        dest=/etc/modules
        line="bcmdhd op_mode=2"
        regexp="^bcmdhd"
    
    - name: Load wlan driver
      command: modprobe bcmdhd
      ignore_errors: yes

    - name: Install nginx
      apt:
        name=nginx
        state=installed
  roles:
    - wap
    - portal
    - vidtest
    - edx_portal
    - kalite

