---
- name: Initial timstamp
  hosts: all
  tasks:
    - shell: echo "Last provisioning started at $(date)" > {{ provision__base_dir }}/provisioning.txt

- name: Main
  hosts: all

  # TODO: Should this go elsewhere?
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded

  include: roles.yml

- name: Closing timestamp
  hosts: all
  tasks:
    - shell: echo "Last provisioning completed $(date)" >> {{ provision__base_dir }}/provisioning.txt
