---
# Basic, common settings
- hosts: all
  tasks:
    - shell: echo "Last provisioning began $(date)" > {{ provision__base_dir }}/provisioning.txt
  roles:
    - { role: provision_base, when: provision_base__enabled is defined and provision_base__enabled }

# Hand off to profiles mapped to groups returned by scripts/inventory.py
#- include: profiles.yml
- include: default.yml
- include: cubietruck.yml
- include: custom.yml


# Timestamp
- hosts: all
  tasks:
    - shell: echo "Last provisioning completed $(date)" >> {{ provision__base_dir }}/provisioning.txt
