---
- name: Initiial timestamp
  hosts: all
  tasks:
    - shell: echo "Last provisioning started at $(date)" > {{ provision__base_dir }}/provisioning.txt

- name: Base Setup
  hosts: all
  # TODO: Should this go elsewhere?
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
  tasks:
    - name: Install nginx
      apt:
        name=nginx
        state=installed
  roles:
    - provision_base

- name: Cubietruck playbook
  hosts: cubietruck
  include: cubietruck.yml

- name: Closing timestamp
  hosts: all
  tasks:
    - shell: echo "Last provisioning completed $(date)" >> {{ provision__base_dir }}/provisioning.txt
