---
- hosts: all
  tasks:
    - shell: echo "Last provisioning started at $(date)" > {{ provision__base_dir }}/provisioning.txt

  include: roles.yml
      
  # TODO: This should go elsewhere...
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded

# Timestamp
- hosts: all
  tasks:
    - shell: echo "Last provisioning completed $(date)" >> {{ provision__base_dir }}/provisioning.txt
