---
- name: Initiial timestamp
  hosts: all
  # TODO: Should this go elsewhere?
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded

  tasks:
    - shell: echo "Last provisioning started at $(date)" > {{ provision__base_dir }}/provisioning.txt

- name: cubietruck ethernet setup
  hosts: cubietruck
  tasks:
    - name: Configure wlan driver
      lineinfile:
        dest=/etc/modules
        line="bcmdhd op_mode=2"
        regexp="^bcmdhd"
    
    - name: Load wlan driver
      command: modprobe bcmdhd
      ignore_errors: yes

- name: Base Setup
  hosts: all
  roles:
    - provision_base

- name: Supporting roles
  hosts: all

  tasks:
    - name: Install nginx
      apt:
        name=nginx
        state=installed

  include: roles.yml

- name: Closing timestamp
  hosts: all
  tasks:
    - shell: echo "Last provisioning completed $(date)" >> {{ provision__base_dir }}/provisioning.txt
