---
- name: Installing portal dependencies
  apt:
    name={{ item }}
    state=installed
  with_items:
     - nginx
     - php5
     - php5-fpm
     - conntrack
     - psmisc

- name: Nginx should be running
  service:
    name=nginx
    state=started

- name: PHP FPM should be running
  service:
    name=php5-fpm
    state=started

- name: Remove nginx default page
  file:
    path={{ provision__sites_enabled_dir }}/default
    state=absent
  notify: reload nginx

# TODO: This is an ugly hack. There's probably a better way.
- name: Changing default edx lms port
  lineinfile:
    dest={{ provision__sites_available_dir }}/lms 
    regexp='^(\s*)listen' 
    backrefs=yes 
    line='\1listen {{ EDXAPP_LMS_NGINX_PORT }} default' 
    state=present
  when: edx__pre_installed is defined and edx__pre_installed

- name: Installing rmtrack script
  copy:
    src=rmtrack
    dest=/usr/bin/
    mode=0755

- include: captive.yml
  when: portal__require_login

- name: Create site content dirs
  file: 
    path={{ item }}
    state=directory
    owner=root group={{ common_web_user }} mode=755 
  with_items:
    - "{{ portal__docroot }}"
    - "{{ portal__redirects }}"

- name: Install portal landing page
  template:
    src=site/index.php.j2
    dest={{ portal__docroot }}/index.php

- name: Deploy site config
  template:
    src=nginx/portal.j2
    dest={{ portal__base }}/portal.conf
    owner=root group={{ common_web_user }} mode=0640

- name: Activate site config
  file:
    src={{ portal__base }}/portal.conf
    dest={{ provision__sites_enabled_dir }}/portal
    state=link owner=root group=root
  notify: reload nginx
  
- include: portal_site.yml
