---
- shell: echo "{{ portal__subsites }}" | tee /tmp/subsites
    
- name: Deploy subsite redirect instructions
  template:
    src=nginx/nginx_portal_redirect.j2
    dest={{ portal__redirects }}/{{ item.name }}
    owner=root group={{ common_web_user }} mode=0640
  with_items: portal__subsites
    
## This should be the job of the subsite's role
#- name: Create subsite content dirs
#  file: 
#    path={{ item.docroot }}
#    state=directory
#    owner=root group={{ common_web_user }} mode=755 
#  with_items: portal__subsites
#
#- name: Deploy subsite content
#  template:
#    src=site/index.html.j2
#    dest={{ item.docroot }}/index.html
#  with_items: portal__subsites
#- name: Deploy subsite config
#  template:
#    src=config/nginx_server.j2
#    dest={{ nginx_sites_available_dir }}/vidtest
#    owner=root group={{ common_web_user }} mode=0640
#  with_items: portal__subsites
#
#- name: Activate subsite config
#  file:
#    src={{ nginx_sites_available_dir }}/vidtest
#    dest={{ nginx_sites_enabled_dir }}/vidtest
#    state=link owner=root group=root
#  with_items: portal__subsites
#  notify: reload nginx
